name: Build PDF
on: [push]
jobs:
  build_latex:
    name: latexmk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
      - uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: cv.pdf
